### ISSUE TITLE
Error on disabled

### ISSUE THREAD

**Issue by Schrank** [tobihille/api-model-bridge#2]
It would be great if 

```
if ( !Mage::getStoreConfig('api/apimodelbridge/enable') )
    {
      return json_encode($data);
    }
```

would return an error, rather than an empty array.

**Comment by tobihille** [comment]
I think I will add a config (if you want default enabled) which adds this funtionality so we can maintain the old behaviour while adding the option to return a failiure. Sounds great?
What is your preferred default?
Or even better, do you have fixed it already and can provide a PR? ;)

Sorry btw. i was in holidays and didn't wanted do do anything regarding web ;)

**Comment by Schrank** [comment]
No need to be sorry. It is open source, so expecting support is the wrong way :) No PR. Found the problem, and turned the module on :)

And you should turn on the module by default. I'm installing it to use it!

**Comment by tobihille** [comment]
Fixed.

Added config to throw faults or return emtpy data and followed your suggestion to enable the module by default.
Return faults instead of empty data is default now
